### ISSUE TITLE
Sweep: It looks like an issue has occurred around fetching the files

### ISSUE THREAD

**Issue by nas-maker** [sweepai/sweep#3167]
i get this error :  Traceback (most recent call last):
webhook  |   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
webhook  |     self.run()
webhook  |   File "/usr/local/lib/python3.10/threading.py", line 953, in run
webhook  |     self._target(*self._args, **self._kwargs)
webhook  |   File "/app/sweepai/api.py", line 145, in run_on_ticket
webhook  |     return on_ticket(*args, **kwargs, tracking_id=tracking_id)
webhook  |   File "/app/sweepai/handlers/on_ticket.py", line 1595, in on_ticket
webhook  |     raise e
webhook  |   File "/app/sweepai/handlers/on_ticket.py", line 726, in on_ticket
webhook  |     raise Exception("Failed to fetch files") 
self hosting

<details open>
<summary>Checklist</summary>

- [X] Modify `sweepai/handlers/on_ticket.py` ! No changes made  [Edit](https://github.com/sweepai/sweep/edit/sweep/it_looks_like_an_issue_has_occurred_arou/sweepai/handlers/on_ticket.py)
- [X] Running GitHub Actions for `sweepai/handlers/on_ticket.py` ✗  [Edit](https://github.com/sweepai/sweep/edit/sweep/it_looks_like_an_issue_has_occurred_arou/sweepai/handlers/on_ticket.py)
</details>

**Comment by MartinYe1234** [comment]
<div align='center'><a href="https://github.com/sweepai/sweep"><img class="swing" src="https://raw.githubusercontent.com/sweepai/sweep/main/.assets/sweeping.gif" width="100" style="width:50px; margin-bottom:10px" alt="Sweeping"></a></div><br/><div align='center'>

<img src='https://progress-bar.dev/0/?&title=Progress&width=600' alt='0%' /></div>

<div align='center'>💎 <b>Sweep Pro</b>: I'm using GPT-4. You have unlimited GPT-4 tickets. (tracking ID: <code>None</code>)</div>

---
> [!TIP]
> I can email you when I complete this pull request if you set up your email [here](https://progress.sweep.dev/profile)!

---
## Actions (click)
- [ ] ↻ Restart Sweep

---
I am currently looking into this ticket! I will update the progress of the ticket in this comment. I am currently searching through your code, looking for relevant snippets.

---
## Step 1: 🔎 Searching
I'm searching for relevant snippets in your repository. If this is your first time using Sweep, I'm indexing your repository. You can monitor the progress using the progress dashboard

---

<details>
<summary><b>🎉 Latest improvements to Sweep:</b></summary>
<ul>
<li>New <a href="https://progress.sweep.dev">dashboard</a> launched for real-time tracking of Sweep issues, covering all stages from search to coding.</li>
<li>Integration of OpenAI's latest Assistant API for more efficient and reliable code planning and editing, improving speed by 3x.</li>
<li>Use the <a href="https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github">GitHub issues extension</a> for creating Sweep issues directly from your editor.</li>
</ul>
</details>


💡 To recreate the pull request edit the issue title or description.
<sup>Something wrong? [Let us know](https://discord.gg/sweep).</sup>
