### ISSUE TITLE
Sweep: Regex matching bug

### ISSUE THREAD

**Issue by kevinlu1248** [sweepai/sweep#578]
### Description

```
2023-07-18 19:01:47.365 | WARNING  | sweepai.core.sweep_bot:modify_file:388 - Recieved error 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/root/sweepai/core/sweep_bot.py", line 374, in modify_file
    new_file = generate_new_file(modify_file_response, contents, chunk_offset=chunk_offset)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/sweepai/utils/diff.py", line 116, in generate_new_file
    new_file = re.search(r".*?<new_file>\n?(.*)\n<\/new_file>", modify_file_response, re.DOTALL).group(1)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by kevinlu1248** [comment]
sweep: retry
