### ISSUE TITLE
Sweep: Fix the following issue

### ISSUE THREAD

**Issue by kevinlu1248** [sweepai/sweep#646]
### Description

Log:

```
2023-07-20 01:41:59.029 | ERROR    | sweepai.handlers.on_ticket:on_ticket:418 - Traceback (most recent call last):
  File "/root/sweepai/handlers/on_ticket.py", line 404, in on_ticket
    changes_required, review_comment = review_pr(repo=repo, pr=pr, issue_url=issue_url, username=username,
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/sweepai/handlers/on_review.py", line 82, in review_pr
    review_prompt_constructed = review_message.construct_prompt()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/sweepai/utils/prompt_constructor.py", line 95, in construct_prompt
    file_name, new_file_contents, old_file_contents, file_patch = self.diff
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 4, got 2)
```

**Comment by kevinlu1248** [comment]
This solution isn't really right
